### ISSUE TITLE
可以帮忙看一下用nuitka打包后双击exe啥反应也没有的问题么

### ISSUE THREAD

**Issue by supersu097** [zhiyiYo/Groove#45]
**Describe the bug**
用nuitka打包后双击exe啥反应也没有
**To Reproduce**
打包命令为：
python -m nuitka --follow-imports --standalone --enable-plugin=pyqt5 --windows-disable-console --enable-plugin=numpy .\Groove.py
另外参考网上的资料在groove.py中加入了两行代码，为了解决提示某dll缺失的问题
```
import sys, os
if hasattr(sys, 'frozen'):
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']
```
**Expected behavior**

**Environment(please complete the following information):**
 - OS: Win10 21h2
 - DPI scaling: [e.g. 125%]

**Additional context**
我用上述命令打包了一个叫cleanmywechat的pyqt5应用，运行正常

**Comment by zhiyiYo** [comment]
@supersu097 
表示没用过这个工具来打包 app，你可以在终端运行  `.\Groove.exe`  看下有无报错信息

**Comment by supersu097** [comment]
终端直接运行`python Groove.py`界面正常弹出来，但是终端运行编译好的Groove.exe就啥反应也没有，btw，之所以用这个来打包是因为冷启动速度肉眼可见的提升，这个诱惑力对于我来说实在太大了。


> @supersu097 表示没用过这个工具来打包 app，你可以在终端运行 `.\Groove.exe` 看下有无报错信息

**Comment by zhiyiYo** [comment]
🤔 pyinstaller 打包之后速度也没慢多少吧

**Comment by supersu097** [comment]
> 🤔 pyinstaller 打包之后好像速度也没慢多少吧

是还挺快，但是一个启动要三四秒一个只要一两秒还是觉得香一些~

**Comment by zhiyiYo** [comment]
因为没捣鼓过 nuitka，所以帮不上啥忙🥲

**Comment by supersu097** [comment]
> 因为没捣鼓过 nuitka，所以帮不上啥忙🥲

如果没啥事的话帮忙捣鼓一些呗~

**Comment by supersu097** [comment]
```2022-10-10 20:39:52,840 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "D:\Mini-Projects\CleanMyWechat-master\app\Groove.dist\Groove.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Mini-Projects\CleanMyWechat-master\app\Groove.dist\View\main_window\__init__.py", line 1, in <module View.main_window>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Mini-Projects\CleanMyWechat-master\app\Groove.dist\View\main_window\main_window.py", line 27, in <module View.main_window.main_window>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Mini-Projects\CleanMyWechat-master\app\Groove.dist\components\label_navigation_interface.py", line 4, in <module components.label_navigation_interface>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Mini-Projects\CleanMyWechat-master\app\Groove.dist\pinyin\__init__.py", line 3, in <module pinyin>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "D:\Mini-Projects\CleanMyWechat-master\app\Groove.dist\pinyin\pinyin.py", line 16, in <module pinyin.pinyin>
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Mini-Projects\\CleanMyWechat-master\\app\\Groove.dist\\pinyin\\Mandarin.dat'****
``` 找到原因了哈
