### ISSUE TITLE
一扫描本地歌曲就报FileNotFoundError: [WinError 3] 系统找不到指定的路径

### ISSUE THREAD

**Issue by supersu097** [zhiyiYo/Groove#47]
**Describe the bug**
一扫描本地歌曲就报FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'cache\\Album_Cover\\July_Time...'
然后启动也会报这个，然后就再也启动不了主界面了。
```
2022-10-12 22:05:47,050 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "View\main_window\main_window.py", line 1312, in onReloadFinished
  File "View\my_music_interface\my_music_interface.py", line 166, in updateWindow
  File "View\my_music_interface\album_tab_interface\album_tab_interface.py", line 35, in updateWindow
  File "View\my_music_interface\album_tab_interface\album_card_interface.py", line 327, in updateAllAlbumCards
  File "components\album_card\album_card_base.py", line 34, in __init__
  File "components\album_card\album_card_base.py", line 128, in __setAlbumInfo
  File "common\cover.py", line 46, in path
  File "common\cover.py", line 46, in <listcomp>
  File "pathlib.py", line 1140, in glob
  File "pathlib.py", line 534, in _select_from
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'cache\\Album_Cover\\July_Time...'
```
**To Reproduce**

**Expected behavior**

**Environment(please complete the following information):**
 - OS: win10 21h2
 - DPI scaling: [e.g. 125%]

**Additional context**
如果需要我提供我的本地歌曲库来复现的话，我可以打包上传到阿里云盘给你验证一下哈~

**Comment by zhiyiYo** [comment]
感谢反馈，麻烦上传一下歌曲库（包含专辑是 July_Time 的那一首再加一两首就好）

**Comment by zhiyiYo** [comment]
目前猜测是这首歌曲没有专辑封面文件夹导致 `path.glob()` 报错：
```python
    def path(self, coverType=CoverType.ALBUM_BIG) -> str:
        """ get cover path

        Parameters
        ----------
        coverType: CoverType
            cover type
        """
        cover = coverType.value
        folder = albumCoverFolder / self.name
        files = [i for i in folder.glob('*') if i.is_file()]

        # use the first image file in directory
        if files and files[0].suffix.lower() in (".png", ".jpg", ".jpeg", ".jiff", ".gif"):
            cover = str(files[0])

        return cover
```

**Comment by supersu097** [comment]
> 目前猜测是这首歌曲没有专辑封面文件夹导致 `path.glob()` 报错：
> 
> ```python
>     def path(self, coverType=CoverType.ALBUM_BIG) -> str:
>         """ get cover path
> 
>         Parameters
>         ----------
>         coverType: CoverType
>             cover type
>         """
>         cover = coverType.value
>         folder = albumCoverFolder / self.name
>         files = [i for i in folder.glob('*') if i.is_file()]
> 
>         # use the first image file in directory
>         if files and files[0].suffix.lower() in (".png", ".jpg", ".jpeg", ".jiff", ".gif"):
>             cover = str(files[0])
> 
>         return cover
> ```

我刚看了一下在windows和mac下面都是有封面的哦，稍等一下，阿里云盘不让分享压缩包和mp3，我正在传到别的网盘~

**Comment by supersu097** [comment]
https://mega.nz/file/dEdHjTgK#OQh8bJhY7SK1gdDopGNMgyBvY09XU1Dwn39avAjhOJU 
你试一下这个可以不~

**Comment by zhiyiYo** [comment]
行，吃完饭试试

**Comment by zhiyiYo** [comment]
@supersu097 
应该是专辑名字的锅，专辑名是 `Time...`，但是 `pathlib` 创建的文件夹是 `Time`，而我在调整专辑名字的时候没有把 ``...` 去掉

**Comment by supersu097** [comment]
> @supersu097 应该是专辑名字的锅，专辑名是 `Time...`，但是 `pathlib` 创建的文件夹是 `July_Time`，而我在调整专辑名字的时候没有把 `...` 去掉，接着去不存在的 `July_Time...` 文件夹中寻找封面图片就引发了错误

这个感觉不太好处理吧，不像空格直接`strip()`一下就好了，毕竟可能有各种符号出现~

**Comment by zhiyiYo** [comment]
把 `app/common/os_utils.py` 的 `adjustName()` 函数修改如下就没问题了：
```python
def adjustName(name: str):
    """ adjust file name

    Returns
    -------
    name: str
        file name after adjusting
    """
    name = re.sub(r'[\\/:*?"<>|\r\n]+', "_", name).strip()
    return name.rstrip(".")
```
我这边测试是 ok 的，不知道你那边怎样

**Comment by supersu097** [comment]
> 
可以了，可以了，蟹蟹~

**Comment by supersu097** [comment]
是不报错了，但是专辑封面不缓存了，而且终端疯狂的报下面的错误：
```
2022-10-13 14:59:37,692 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,693 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,694 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,694 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,698 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,699 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,700 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 14:59:37,700 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
```

**Comment by supersu097** [comment]
> 好奇怪，我改了之后就没有这个问题

我是用的你当前的master分支的代码启动的界面，你试试看~

**Comment by zhiyiYo** [comment]
之前分享的文件被删了，能不能直接在这个 issue 里上传一下 zip 文件

**Comment by supersu097** [comment]
> 

好哒，稍等一下哈，我做完核酸了回去上传一下~

**Comment by supersu097** [comment]
[Music.zip](https://github.com/zhiyiYo/Groove/files/9772091/Music.zip)
试一下这个行不

**Comment by zhiyiYo** [comment]
我还是没报错呀

**Comment by supersu097** [comment]
> 我还是没报错呀

会不会是因为我家里的电脑没装readme里面提到的那个依赖导致的呀

**Comment by zhiyiYo** [comment]
你建个虚拟环境试试吧

**Comment by supersu097** [comment]
> 你建个虚拟环境试试吧

我是venv的，我说的是[LAV Filters](https://github.com/Nevcairiel/LAVFilters/releases/download/0.74/LAVFilters-0.74-Installer.exe)这个依赖哈

**Comment by zhiyiYo** [comment]
这个要装的

**Comment by supersu097** [comment]
好的，我来装一下再试试

**Comment by supersu097** [comment]
```
2022-10-13 16:06:47,720 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,721 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,722 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,723 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,727 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,728 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,729 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,731 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:47,732 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:06:50,043 - ERROR - KeyError: 'artists'
2022-10-13 16:06:50,554 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:50,899 - ERROR - KeyError: 'artists'
2022-10-13 16:06:52,291 - ERROR - KeyError: 'artists'
2022-10-13 16:06:53,193 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:53,258 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:53,357 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:53,837 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:56,780 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:57,533 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:06:59,529 - ERROR - KeyError: 'artists'
2022-10-13 16:06:59,765 - ERROR - KeyError: 'artists'
2022-10-13 16:07:04,090 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:07:04,983 - ERROR - KeyError: 'artists'
2022-10-13 16:07:05,037 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-10-13 16:07:08,933 - ERROR - KeyError: 'artists'
2022-10-13 16:07:11,072 - ERROR - KeyError: 'artists'
```
装了也还是不行呢，我放弃了，close掉吧，嘤嘤嘤~

**Comment by zhiyiYo** [comment]
你真的是在那三首歌曲上做的实验吗

**Comment by supersu097** [comment]
> 

额。。抱歉我是在我几百首歌曲上试验的，我来试试那三首哈

**Comment by supersu097** [comment]
> 你真的是在那三首歌曲上做的实验吗

```
(venv) PS D:\tmp\Groove-master\app> python .\Groove.py
D:\tmp\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2022-10-13 16:16:48,850 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:16:48,851 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:16:48,854 - ERROR - OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ':\\images\\default_covers\\album_200_200.png'
2022-10-13 16:16:49,194 - ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0
```
额。。这三首也是同样的报错呢，你看刚好三个WinError 123

**Comment by zhiyiYo** [comment]
把cache文件夹删了试试

**Comment by zhiyiYo** [comment]
我只在那三个文件上测试也不会出问题

**Comment by supersu097** [comment]
> 把cache文件夹删了试试

好的

**Comment by supersu097** [comment]
[Uploading Groove-master.zip…]()
你用我这个按你说的改好的代码直接运行试一下

**Comment by zhiyiYo** [comment]
你没传上来

**Comment by supersu097** [comment]
> 把cache文件夹删了试试

刚删了，还是同样的报错哦

**Comment by supersu097** [comment]
> 你没传上来

在传了，100KB的小水管有点慢~

**Comment by supersu097** [comment]
[Groove-master.zip](https://github.com/zhiyiYo/Groove/files/9772423/Groove-master.zip)
可以了，试一下哈

**Comment by zhiyiYo** [comment]
没报错呀

**Comment by zhiyiYo** [comment]
你要不从头录制一遍你的操作

**Comment by supersu097** [comment]
https://user-images.githubusercontent.com/7045106/195556139-4ddf18f7-3500-489d-9c55-8a141d5bc810.mp4

录制好了，你看看哈~

**Comment by zhiyiYo** [comment]
奇怪，为什么你还是会报无法播放的问题，如果正确安装了 LAV Filters 应该不会有这个问题的

**Comment by supersu097** [comment]
> 奇怪，为什么你还是会报无法播放的问题，如果正确安装了 LAV Filters 应该不会有这个问题的

我印象中没装LAV Filters之前可以正常播放，有歌词，除了没封面外都正常，装了之后反倒不能播放了，奇怪了~

**Comment by zhiyiYo** [comment]
能播放的应该是 mp3，装了 LAVFilters 时候才能播放 flac 等格式的

**Comment by supersu097** [comment]
> 能播放的应该是 mp3，装了 LAVFilters 时候才能播放 flac 等格式的

装和没装之前都是放的mp3哦

**Comment by zhiyiYo** [comment]
对，不装 LAVFilters 也能播放 mp3，但是其他格式的没有 LAV Filters 播放不了

**Comment by supersu097** [comment]
> 对，不装 LAVFilters 也能播放 mp3，但是其他格式的没有 LAV Filters 播放不了

先暂时close掉吧，不耽误你的时间了哈~
