### ISSUE TITLE
External Drives.

### ISSUE THREAD

**Issue by Crocodile73** [zhiyiYo/Groove#86]
open and add external drive to library,

2023-09-05 12:09:03,854 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "common\thread\library_thread.py", line 35, in run
  File "common\library\library.py", line 89, in setDirectories
  File "common\library\file_system.py", line 61, in setDirs
  File "common\library\file_system.py", line 104, in addDirs
  File "common\library\file_system.py", line 82, in addDir
  File "common\library\file_system.py", line 82, in addDir
  File "common\library\file_system.py", line 72, in addDir
  File "common\library\directory.py", line 26, in __init__
  File "common\library\directory.py", line 34, in glob
  File "common\library\directory.py", line 34, in <listcomp>
  File "pathlib.py", line 1122, in iterdir
PermissionError: [WinError 5] Access is denied: 'M:\\$RECYCLE.BIN\\S-1-5-18'

Windows 11 22H2

**Comment by zhiyiYo** [comment]
Try run as admin

**Comment by Crocodile73** [comment]
> Try run as admin

Yeah it gives the same error.
