### ISSUE TITLE
Error trying to make fork of app

### ISSUE THREAD

**Issue by Jake4353** [zhiyiYo/Groove#92]
**Describe the bug**
Multiple errors when trying to run the source code.
when i try to run the source code it gives me this errord
```
2024-03-09 19:54:06,186 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\jacob\Music\Groove\app\Groove.py", line 46, in <module>
    groove = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\View\main_window\main_window.py", line 68, in __init__
    self.createWidgets()
  File "C:\Users\jacob\Music\Groove\app\View\main_window\main_window.py", line 88, in createWidgets
    self.initWindow()
  File "C:\Users\jacob\Music\Groove\app\View\main_window\main_window.py", line 217, in initWindow
    self.resize(w*1240/1920, h*970/1080)
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'float'
  resize(self, w: int, h: int): argument 1 has unexpected type 'float'
```
and even after fixing these errors, i recieve this new error

```
2024-03-09 19:55:26,850 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\jacob\Music\Groove\app\Groove.py", line 46, in <module>
    groove = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\View\main_window\main_window.py", line 68, in __init__
    self.createWidgets()
  File "C:\Users\jacob\Music\Groove\app\View\main_window\main_window.py", line 136, in createWidgets
    self.singerInterface = SingerInterface(
                           ^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\View\singer_interface\singer_interface.py", line 53, in __init__
    self.singerInfoBar = SingerInfoBar(self.singerInfo, self)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\View\singer_interface\singer_info_bar.py", line 21, in __init__
    self.blurLabel = BlurLabel(self.coverPath, 8, self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\View\singer_interface\singer_info_bar.py", line 76, in __init__
    self.setPixmap(getBlurPixmap(imagePath, blurRadius, 0.85))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\common\image_utils.py", line 110, in getBlurPixmap
    image = gaussianBlur(imagePath, blurRadius, brightFactor, blurPicSize)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\common\image_utils.py", line 62, in gaussianBlur
    image = readImage(imagePath)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\Music\Groove\app\common\image_utils.py", line 36, in readImage
    return Image.fromqpixmap(QPixmap(imagePath))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python312\Lib\site-packages\PIL\Image.py", line 3142, in fromqpixmap
    return ImageQt.fromqpixmap(im)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python312\Lib\site-packages\PIL\ImageQt.py", line 86, in fromqpixmap
    return fromqimage(im)
           ^^^^^^^^^^^^^^
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python312\Lib\site-packages\PIL\ImageQt.py", line 75, in fromqimage
    im.save(buffer, "ppm")
TypeError: arguments did not match any overloaded call:
  save(self, fileName: Optional[str], format: Optional[str] = None, quality: int = -1): argument 1 has unexpected type 'QBuffer'
  save(self, device: Optional[QIODevice], format: Optional[str] = None, quality: int = -1): argument 1 has unexpected type 'QBuffer'
```
**To Reproduce**
Steps to reproduce the behavior(you can use GIF to demonstrate :)
1. download souce code
2. run it
3. go to line 217 and 218 of view/main_window/main_window.py
4. put each value in an int() function
5. run again

**Expected behavior**
recieve error

**Environment(please complete the following information):**
 - OS: windows
 - DPI scaling: idk

**Comment by Jake4353** [comment]
Another error i've encountered is with the exe, online music isnt working 

https://github.com/zhiyiYo/Groove/assets/44424544/e20713f8-3a38-4552-83d3-c752ec507333

it wont download, or play anything from online.

**Comment by zhiyiYo** [comment]
Use Python3.8 and Pillow 9.4.0

**Comment by Jake4353** [comment]
Will that fix the downloading from online issue?

**Comment by zhiyiYo** [comment]
Online music sources in China, foreign requests may be blocked
